// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateStudentsInput struct {
	ID                  *int      `json:"id,omitempty"`
	StudentName         *string   `json:"studentName,omitempty"`
	StudentClass        *int      `json:"studentClass,omitempty"`
	StudentRoll         *int      `json:"studentRoll,omitempty"`
	StudentAddress      *string   `json:"studentAddress,omitempty"`
	StudentBloodGroup   *string   `json:"studentBloodGroup,omitempty"`
	StudentMobileNumber *string   `json:"studentMobileNumber,omitempty"`
	DateOfBirth         *string   `json:"dateOfBirth,omitempty"`
	Subject             *Subjects `json:"subject,omitempty"`
	CreatedAt           *string   `json:"createdAt,omitempty"`
	UpdatedAt           *string   `json:"updatedAt,omitempty"`
}

type CreateStudentsResponse struct {
	ID                  int      `json:"Id"`
	StudentName         string   `json:"studentName"`
	StudentClass        int      `json:"studentClass"`
	StudentRoll         int      `json:"studentRoll"`
	StudentAddress      string   `json:"studentAddress"`
	StudentBloodGroup   string   `json:"studentBloodGroup"`
	StudentMobileNumber string   `json:"studentMobileNumber"`
	Score               int      `json:"score"`
	DateOfBirth         string   `json:"dateOfBirth"`
	Subject             *Subject `json:"subject"`
	CreatedAt           string   `json:"createdAt"`
	UpdatedAt           string   `json:"updatedAt"`
}

type GetStudentDetailsInput struct {
	ID int `json:"id"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Subject struct {
	Bengali     float64 `json:"Bengali"`
	English     float64 `json:"English"`
	Mathematics float64 `json:"Mathematics"`
	Physics     float64 `json:"Physics"`
	Biology     float64 `json:"Biology"`
	Chemistry   float64 `json:"Chemistry"`
}

type Subjects struct {
	Bengali     float64 `json:"Bengali"`
	English     float64 `json:"English"`
	Mathematics float64 `json:"Mathematics"`
	Physics     float64 `json:"Physics"`
	Biology     float64 `json:"Biology"`
	Chemistry   float64 `json:"Chemistry"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
